/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_kevinrodriguez;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Kevin
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mod = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenuItem();
        modarbol = new javax.swing.JPopupMenu();
        modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numcuenta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        edad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        genero = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        facul = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        carrer = new javax.swing.JComboBox<>();
        agregar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nombrem = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        apellidom = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        salario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        edadm = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nombrec = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        seccion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        salon = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        si = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        costo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jefe = new javax.swing.JTextField();
        arb = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        arbol1 = new javax.swing.JTree();
        agregar2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lista2 = new javax.swing.JList<>();
        agregar3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lista3 = new javax.swing.JList<>();
        agregar4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        lista4 = new javax.swing.JList<>();
        edificio = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        Modificar.setText("Modificar\n");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        mod.add(Modificar);

        eliminar.setText("Eliminar\n");
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });
        mod.add(eliminar);

        modificar.setText("Modificar\n");
        modarbol.add(modificar);

        Eliminar.setText("Eliminar");
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });
        modarbol.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("Nombre: ");

        jLabel2.setText("ESTUDIANTE");

        jLabel3.setText("Apellido: ");

        jLabel4.setText("Numero de cuenta:");

        numcuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11111223", "15852645", "11236511", "15254456", "18951705", "18954652" }));

        jLabel5.setText("Edad :");

        edad.setModel(new javax.swing.SpinnerNumberModel(15, 15, 100, 1));

        jLabel6.setText("Genero :");

        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel7.setText("Facultad de carrera:");

        facul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Facultad", "Licenciatura", "Ingenieria", "Ciencia de la salud", " " }));
        facul.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                faculItemStateChanged(evt);
            }
        });
        facul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faculActionPerformed(evt);
            }
        });

        jLabel8.setText("Carrera: ");

        carrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrerActionPerformed(evt);
            }
        });

        agregar.setText("Agregar a la Lista estudiante");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        jLabel9.setText("Maestros");

        jLabel10.setText("Nombres:");

        jLabel11.setText("Apellido: ");

        jLabel12.setText("Salario:");

        jLabel13.setText("Edad:");

        edadm.setModel(new javax.swing.SpinnerNumberModel(25, 25, 80, 1));

        lista.setModel(new DefaultListModel());
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        lista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        jLabel15.setText("Clases");

        jLabel16.setText("Nombre:");

        jLabel17.setText("Seccion: ");

        jLabel18.setText("Edificio:");

        jLabel19.setText("Salon:");

        jLabel20.setText("Tiene aire acondicionado:");

        si.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });

        jLabel21.setText("Costo mensual:");

        jLabel22.setText("Jefe de carrera: ");

        arb.setText("Agregar al arbol");
        arb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbMouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        arbol1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(arbol1);

        agregar2.setText("Agregar carrera");
        agregar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar2MouseClicked(evt);
            }
        });

        lista2.setModel(new DefaultListModel());
        lista2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista2MouseClicked(evt);
            }
        });
        lista2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lista2KeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(lista2);

        agregar3.setText("Agregar maestros");
        agregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar3ActionPerformed(evt);
            }
        });

        lista3.setModel(new DefaultListModel());
        lista3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista3MouseClicked(evt);
            }
        });
        lista3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lista3KeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(lista3);

        agregar4.setText("Agregar clase");
        agregar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar4ActionPerformed(evt);
            }
        });

        lista4.setModel(new DefaultListModel());
        lista4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista4MouseClicked(evt);
            }
        });
        lista4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lista4KeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(lista4);

        edificio.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));

        jLabel23.setText("PARA ELIMINAR PRECIONAR LA TECLA DELETE");

        jLabel24.setText("PARA PODER MODIFICAR RELLENAR LA CASILLA QUE DESEA MODIFICAR ANTES DE DARLE MODIFICAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2)
                        .addGap(251, 251, 251)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(207, 207, 207))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(agregar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(110, 110, 110))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(127, 127, 127)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombrem, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(apellidom)
                                    .addComponent(salario)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(edadm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombrec, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(edificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(salon, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(26, 26, 26)
                                        .addComponent(si, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(agregar2)
                                .addGap(152, 152, 152)
                                .addComponent(agregar3)
                                .addGap(229, 229, 229)
                                .addComponent(agregar4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(facul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(carrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jefe))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(arb))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(291, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(197, 197, 197)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(nombrem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addComponent(nombrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11)
                                        .addComponent(apellidom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(numcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(edadm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18)
                                            .addComponent(edificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(63, 63, 63))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(salon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(si, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel15)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(facul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(carrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel21))
                    .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(agregar2)
                    .addComponent(agregar3)
                    .addComponent(agregar4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(arb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(441, 441, 441)
                    .addComponent(jLabel24)
                    .addContainerGap(609, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        DefaultListModel modelo = (DefaultListModel) lista.getModel();
        modelo.addElement(new estudiantes(nombre.getText(),apellido.getText(),numcuenta.getSelectedItem().toString(),
                (Integer)edad.getValue(),genero.getSelectedItem().toString(),carrer.getSelectedItem().toString()));
        lista.setModel(modelo);
        nombre.setText(null);
        apellido.setText(null);
        edad.setValue(15);
        
    }//GEN-LAST:event_agregarActionPerformed

    private void faculItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_faculItemStateChanged
       
        if (evt.getStateChange()==ItemEvent.SELECTED) {
            if (this.facul.getSelectedIndex()>0) {
                this.carrer.setModel(new DefaultComboBoxModel(this.getcarre(this.facul.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_faculItemStateChanged

    private void carrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrerActionPerformed
      
    }//GEN-LAST:event_carrerActionPerformed

    private void faculActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faculActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faculActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        if (lista.getSelectedIndex()>= 0) {
            DefaultListModel modificar =(DefaultListModel) lista.getModel();
            ((estudiantes)modificar.get(lista.getSelectedIndex())).setNombre(nombre.getText());
            ((estudiantes)modificar.get(lista.getSelectedIndex())).setApellido(apellido.getText());
            ((estudiantes)modificar.get(lista.getSelectedIndex())).setNumero_Cuenta(numcuenta.getSelectedItem().toString());
            ((estudiantes)modificar.get(lista.getSelectedIndex())).setEdad((Integer)edad.getValue());
            ((estudiantes)modificar.get(lista.getSelectedIndex())).setGenero(genero.getSelectedItem().toString());
            ((estudiantes)modificar.get(lista.getSelectedIndex())).setCarrera(carrer.getSelectedItem().toString());
            lista.setModel(modificar);
        }
        if (lista2.getSelectedIndex()>= 0) {
            DefaultListModel modificar =(DefaultListModel) lista2.getModel();
            ((carrera)modificar.get(lista2.getSelectedIndex())).setNombre(nombrem.getText());
            ((carrera)modificar.get(lista2.getSelectedIndex())).setFacultad(facul.getSelectedItem().toString());
            ((carrera)modificar.get(lista2.getSelectedIndex())).setCosto_Mensual(costo.getText());
            ((carrera)modificar.get(lista2.getSelectedIndex())).setJefe_de_carrera(jefe.getText());
            lista2.setModel(modificar);
        }
        if (lista3.getSelectedIndex()>= 0) {
            DefaultListModel modificar =(DefaultListModel) lista3.getModel();
            ((maestros)modificar.get(lista3.getSelectedIndex())).setNombre(nombrem.getText());
            ((maestros)modificar.get(lista3.getSelectedIndex())).setApellido(apellidom.getText());
            ((maestros)modificar.get(lista3.getSelectedIndex())).setEdad((Integer)edadm.getValue());
            lista3.setModel(modificar);
        }
        if (lista4.getSelectedIndex()>= 0) {
            DefaultListModel modificar =(DefaultListModel) lista4.getModel();
            ((clases)modificar.get(lista4.getSelectedIndex())).setNombre(nombrec.getText());
            ((clases)modificar.get(lista4.getSelectedIndex())).setSeccion(seccion.getText());
            ((clases)modificar.get(lista4.getSelectedIndex())).setEdificio((Integer)edificio.getValue());
            ((clases)modificar.get(lista4.getSelectedIndex())).setSalon(salon.getText());
            ((clases)modificar.get(lista4.getSelectedIndex())).setAire_acondicionado(si.getSelectedItem().toString());
            lista4.setModel(modificar);
        }
         
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        if (lista.getSelectedIndex()>= 0) {
            if (evt.isMetaDown()) {
                mod.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_listaMouseClicked

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
        if (lista.getSelectedIndex()>= 0) {
            DefaultListModel modificar =(DefaultListModel) lista.getModel();
            modificar.remove(lista.getSelectedIndex());
            lista.setModel(modificar);
        }
    }//GEN-LAST:event_eliminarMouseClicked

    private void arbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbMouseClicked
    DefaultTreeModel a=(DefaultTreeModel) arbol1.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) a.getRoot();
        DefaultMutableTreeNode nodo;
        nodo=new DefaultMutableTreeNode(new carrera(carrer.getSelectedItem().toString(),facul.getSelectedItem().toString(),costo.getText(),jefe.getText()));
        DefaultMutableTreeNode nodo2;
        nodo2=new DefaultMutableTreeNode (new estudiantes(nombre.getText(),apellido.getText(),numcuenta.getSelectedItem().toString(),
                (Integer)edad.getValue(),genero.getSelectedItem().toString(),carrer.getSelectedItem().toString()));
        DefaultMutableTreeNode carreraa;
        carreraa=new DefaultMutableTreeNode(carrer.getSelectedItem().toString());
         DefaultMutableTreeNode estu;
         estu=new DefaultMutableTreeNode(nombre.getText());
         nodo2.add(estu);
         carreraa.add(estu);
         raiz.add(carreraa);
         a.reload();
    }//GEN-LAST:event_arbMouseClicked

    private void lista2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista2MouseClicked
        if (lista2.getSelectedIndex()>= 0) {
            if (evt.isMetaDown()) {
                mod.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_lista2MouseClicked

    private void agregar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar2MouseClicked
        DefaultListModel modelo2 = (DefaultListModel) lista2.getModel();
        modelo2.addElement(new carrera(carrer.getSelectedItem().toString(),facul.getSelectedItem().toString(),costo.getText(),jefe.getText()));
        lista2.setModel(modelo2);
        costo.setText(null);
        jefe.setText(null);
    }//GEN-LAST:event_agregar2MouseClicked

    private void agregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar3ActionPerformed
       DefaultListModel modelo2 = (DefaultListModel) lista3.getModel();
        modelo2.addElement(new maestros(nombrem.getText(),apellidom.getText(),salario.getText(),(Integer)edadm.getValue()));
        lista3.setModel(modelo2);
        nombrem.setText(null);
        apellidom.setText(null);
        salario.setText(null);
        edadm.setValue(25);
    }//GEN-LAST:event_agregar3ActionPerformed

    private void lista3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista3MouseClicked
        if (lista3.getSelectedIndex()>= 0) {
            if (evt.isMetaDown()) {
                mod.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_lista3MouseClicked

    private void agregar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar4ActionPerformed
       DefaultListModel modelo2 = (DefaultListModel) lista4.getModel();
        modelo2.addElement(new clases(nombrec.getText(),seccion.getText(),(Integer)edificio.getValue(),salon.getText(),si.getSelectedItem().toString()));
      
        lista4.setModel(modelo2);
        nombrec.setText(null);
        seccion.setText(null);
        salon.setText(null);
        edificio.setValue(0);
    }//GEN-LAST:event_agregar4ActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siActionPerformed

    private void lista4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista4MouseClicked
        if (lista4.getSelectedIndex()>= 0) {
            if (evt.isMetaDown()) {
                mod.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_lista4MouseClicked

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        
    }//GEN-LAST:event_EliminarMouseClicked

    private void listaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaKeyPressed
        if (evt.getKeyCode()==evt.VK_DELETE) {
            if (lista.getSelectedIndex()>= 0) {
            DefaultListModel modificar =(DefaultListModel) lista.getModel();
            modificar.remove(lista.getSelectedIndex());
            lista.setModel(modificar);
        }
      }
    }//GEN-LAST:event_listaKeyPressed

    private void lista2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lista2KeyPressed
       if (evt.getKeyCode()==evt.VK_DELETE) {
            if (lista2.getSelectedIndex()>= 0) {
            DefaultListModel modificar =(DefaultListModel) lista2.getModel();
            modificar.remove(lista2.getSelectedIndex());
            lista2.setModel(modificar);
        }
      }
    }//GEN-LAST:event_lista2KeyPressed

    private void lista3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lista3KeyPressed
        if (evt.getKeyCode()==evt.VK_DELETE) {
            if (lista3.getSelectedIndex()>= 0) {
            DefaultListModel modificar =(DefaultListModel) lista3.getModel();
            modificar.remove(lista3.getSelectedIndex());
            lista3.setModel(modificar);
        }
      }
    }//GEN-LAST:event_lista3KeyPressed

    private void lista4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lista4KeyPressed
      if (evt.getKeyCode()==evt.VK_DELETE) {
            if (lista4.getSelectedIndex()>= 0) {
            DefaultListModel modificar =(DefaultListModel) lista4.getModel();
            modificar.remove(lista4.getSelectedIndex());
            lista4.setModel(modificar);
        }
      }
    }//GEN-LAST:event_lista4KeyPressed
    public String[] getcarre(String facul){
        String [] carrera=new String[5];
        if (facul.equals("Licenciatura")) {
            carrera[0]="Finanzas";
            carrera[1]="Derecho";
            carrera[2]="Administracion_de_Empresa";
            carrera[3]="Diseño_Grafico";
            carrera[4]="Mercadotecnia";
        }
        if (facul.equals("Ingenieria")) {
            carrera[0]="Sistemas computacionales";
            carrera[1]="Industrial y sistemas";
            carrera[2]="mecatronica";
            carrera[3]="biomedica";
            carrera[4]="energia";
        }
         if (facul.equals("Ciencia de la salud")) {
            carrera[0]="Medicina y cirugia";
            carrera[1]="odontologia";
            carrera[2]="Nutrición";
            carrera[3]="Terapia fisica y ocupacional";
        }
         return carrera;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JButton agregar;
    private javax.swing.JButton agregar2;
    private javax.swing.JButton agregar3;
    private javax.swing.JButton agregar4;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField apellidom;
    private javax.swing.JButton arb;
    private javax.swing.JTree arbol1;
    private javax.swing.JComboBox<String> carrer;
    private javax.swing.JTextField costo;
    private javax.swing.JSpinner edad;
    private javax.swing.JSpinner edadm;
    private javax.swing.JSpinner edificio;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JComboBox<String> facul;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jefe;
    private javax.swing.JList<String> lista;
    private javax.swing.JList<String> lista2;
    private javax.swing.JList<String> lista3;
    private javax.swing.JList<String> lista4;
    private javax.swing.JPopupMenu mod;
    private javax.swing.JPopupMenu modarbol;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombrec;
    private javax.swing.JTextField nombrem;
    private javax.swing.JComboBox<String> numcuenta;
    private javax.swing.JTextField salario;
    private javax.swing.JTextField salon;
    private javax.swing.JTextField seccion;
    private javax.swing.JComboBox<String> si;
    // End of variables declaration//GEN-END:variables
}
